# https://supabase.com/docs/guides/cli/config
project_id = "zapifica"

[functions.process-scheduled-messages]
verify_jwt = false

[functions.evolution-whatsapp-webhook]
verify_jwt = false

[functions.inbox-ai-reply]
verify_jwt = false

[functions.process-ai-training]
verify_jwt = true

[functions.apify-extractor]
verify_jwt = true

[functions.apify-webhook]
verify_jwt = false
