-- ============================================================================
-- Central de Treinamento da IA (Base de Conhecimento)
-- ============================================================================

-- 1) Enum/type de materiais
do $$ begin
  create type public.ai_training_material_type as enum ('text', 'link', 'file');
exception
  when duplicate_object then null;
end $$;

-- 2) Materiais (multi-tenant por user_id)
create table if not exists public.ai_training_materials (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  type public.ai_training_material_type not null default 'text',
  content text,
  url text,
  is_processed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_training_materials_content_or_url_check check (
    (type = 'text' and content is not null and length(trim(content)) > 0)
    or (type = 'link' and url is not null and length(trim(url)) > 0)
    or (type = 'file')
  )
);

create index if not exists ai_training_materials_user_created_idx
  on public.ai_training_materials (user_id, created_at desc);

alter table public.ai_training_materials enable row level security;

drop policy if exists "ai_training_materials_select_own" on public.ai_training_materials;
create policy "ai_training_materials_select_own"
  on public.ai_training_materials for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "ai_training_materials_insert_own" on public.ai_training_materials;
create policy "ai_training_materials_insert_own"
  on public.ai_training_materials for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "ai_training_materials_update_own" on public.ai_training_materials;
create policy "ai_training_materials_update_own"
  on public.ai_training_materials for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "ai_training_materials_delete_own" on public.ai_training_materials;
create policy "ai_training_materials_delete_own"
  on public.ai_training_materials for delete
  to authenticated
  using (auth.uid() = user_id);

comment on table public.ai_training_materials is
  'Materiais adicionados pelo usuário para treinar a IA (texto/link/arquivo).';

-- 3) Contexto da empresa (uma linha por usuário)
create table if not exists public.ai_company_context (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  master_prompt text not null default '',
  company_summary text not null default '',
  updated_at timestamptz not null default now(),
  constraint ai_company_context_user_unique unique (user_id)
);

create index if not exists ai_company_context_user_idx
  on public.ai_company_context (user_id);

alter table public.ai_company_context enable row level security;

drop policy if exists "ai_company_context_select_own" on public.ai_company_context;
create policy "ai_company_context_select_own"
  on public.ai_company_context for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "ai_company_context_insert_own" on public.ai_company_context;
create policy "ai_company_context_insert_own"
  on public.ai_company_context for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "ai_company_context_update_own" on public.ai_company_context;
create policy "ai_company_context_update_own"
  on public.ai_company_context for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "ai_company_context_delete_own" on public.ai_company_context;
create policy "ai_company_context_delete_own"
  on public.ai_company_context for delete
  to authenticated
  using (auth.uid() = user_id);

comment on table public.ai_company_context is
  'Configurações e resumo mestre por usuário para orientar a IA. Uma linha por user_id.';

-- 4) Trigger updated_at (reusa utilitário se existir; cria se não existir)
create or replace function public.tg_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists ai_training_materials_touch_updated_at on public.ai_training_materials;
create trigger ai_training_materials_touch_updated_at
  before update on public.ai_training_materials
  for each row execute function public.tg_touch_updated_at();

create or replace function public.tg_touch_ai_company_context_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists ai_company_context_touch_updated_at on public.ai_company_context;
create trigger ai_company_context_touch_updated_at
  before update on public.ai_company_context
  for each row execute function public.tg_touch_ai_company_context_updated_at();

